# Generated by Django 3.2 on 2021-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=200)),
                ('projectcatagory', models.CharField(blank=True, choices=[('Web Design', 'Web Design'), ('web development', 'Web Development')], max_length=30, null=True)),
                ('websitelink', models.TextField(blank=True, default='#', null=True)),
            ],
        ),
    ]
