# Generated by Django 3.2 on 2021-05-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_recentproject_projectcatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentproject',
            name='Picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
