# Generated by Django 3.2 on 2021-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_recentproject_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentproject',
            name='Picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
