# Generated by Django 3.2.3 on 2021-06-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_recentproject_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentproject',
            name='projectcatagory',
            field=models.CharField(blank=True, choices=[('Web Design', 'Web Design'), ('web development', 'Web Development'), ('Wordpress', 'wordpress')], max_length=60, null=True),
        ),
    ]
